name: 'next-semver-action'
description: 'A GitHub action that generates the next semantic version and creates a release'
author: 'MECLab'
inputs:
  bump:
    description: 'The semantic version that is to be bumped. Either major, minor or patch'
    required: true

  bump_patch_by_default:
    description: 'bump the patch number by default when no bump label is supplied'
    required: false
    default: 'false'

#  token:
#    description: 'GitHub api token i.e. github.token'
#    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
